/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { PrismaBase } from '../../interfaces';

/**
 * Updates your database using migrations during development and creates the database if it does not exist.
 */
export interface MigrateExecutorSchema extends PrismaBase {
  /**
   * The name of the migration.
   */
  name: string;
  /**
   * Creates a new migration based on the changes in the schema but does not apply that migration.
   */
  'create-only'?: boolean;
  /**
   * Skip triggering seed.
   */
  'skip-seed'?: boolean;
  /**
   * Skip triggering generators (for example, Prisma Client).
   */
  'skip-generate'?: boolean;
}
