/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { PrismaBase } from '../../interfaces';

/**
 * The db pull command connects to your database and adds Prisma models to your Prisma schema that reflect the current database schema.
 */
export interface PullExecutorSchema extends PrismaBase {
  /**
   * Force overwrite of manual changes made to schema. The generated schema will be based on the introspected schema only.
   */
  force?: boolean;
  /**
   * Prints the created schema.prisma to the screen instead of writing it to the filesystem.
   */
  print?: boolean;
}
