/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Connects to your database and adds Prisma models to your Prisma schema that reflect the current database schema.
 */
export interface PrismaPullSchema {
  /**
   * The path to the prisma schema eg. 'prisma/schema.prisma'
   */
  schema?: string;
  /**
   * Optional flags
   */
  options?: {
    /**
     * Force overwrite of manual changes made to schema.
     */
    force?: boolean;
    /**
     * Prints the created schema.prisma to the screen instead of writing it to the filesystem.
     */
    print?: boolean;
  };
}
