name: 🚀 Feature request
description: This form is to suggest an idea for this project.
labels: ['type: enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking your precious time to file a feature request! 🙏 We are excited to hear your ideas and want to make this project better for everyone.

        Please provide as much detail as possible about the feature you are requesting. The more information you provide, the easier it will be for us to understand and implement your request.
  - type: textarea
    id: feature-description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: feature-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: feature-alternative
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
