export * from './lib/cvb.js';
export type {
  ClassDictionary,
  ClassProp,
  ClassValue,
  Compose,
  CX,
  CXOptions,
  CXReturn,
  DefineConfig,
  DefineConfigOptions,
  RecipeCreatorFn,
  RecipeDefinition,
  RecipeSelection,
  RecipeVariantFn,
  RecipeVariantRecord,
  SlotRecipeCreatorFn,
  SlotRecipeDefinition,
  SlotRecipeVariantFn,
  SlotRecipeVariantRecord,
  VariantProps,
} from './lib/types.js';
