/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

type Engine = 'docker' | 'podman' | 'kaniko';
type Template = 'empty' | 'nest' | 'next' | 'nginx';

export interface ConfigurationGeneratorSchema {
  /**
   * The name of the project to add the Container setup to.
   */
  project: string;
  /**
   * Provide the container engine to be used.
   * @default docker
   */
  engine?: Engine & {};
  /**
   * Which type of app you are building?.
   * @default empty
   */
  template?: Template & {};
  /**
   * Skips formatting the workspace after the generator completes.
   * @default false
   */
  skipFormat?: boolean;
}
