/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { PrismaBase } from '../../interfaces';

/**
 * This command deletes and recreates the database, or performs a 'soft reset' by removing all data, tables, indexes, and other artifacts.
 */
export interface ResetExecutorSchema extends PrismaBase {
  /**
   * Skip the confirmation prompt.
   */
  force: boolean;
  /**
   * Skip triggering generators (for example, Prisma Client).
   */
  'skip-generate'?: boolean;
  /**
   * Skip triggering seed.
   */
  'skip-seed'?: boolean;
}
