/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { PrismaBase } from '../../interfaces';

/**
 * The migrate resolve command allows you to solve migration history issues in production by marking a failed migration as already applied (supports baselining) or rolled back.
 */
export interface ResolveExecutorSchema extends PrismaBase {
  /**
   * Record a specific migration as applied - for example --applied '20201231000000_add_users_table'
   */
  applied?: string;
  /**
   * Record a specific migration as rolled back - for example --rolled-back '20201231000000_add_users_table'.
   */
  'rolled-back'?: string;
}
