/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { PrismaBase } from '../../interfaces';

/**
 * Formats the Prisma Schema Language of the Prisma schema file.
 */
export type FormatExecutorSchema = PrismaBase;
